# Generated by Django 3.2.3 on 2021-05-27 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default=None, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120)),
                ('age_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daycares.agegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Daycare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('street_address', models.CharField(max_length=75, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('images', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(max_length=250)),
                ('min_cost_estimate', models.CharField(max_length=4)),
                ('max_cost_estimate', models.CharField(max_length=4)),
                ('teacher_child_ratio', models.CharField(max_length=15)),
                ('availability', models.BooleanField(default=True)),
                ('infant_group', models.BooleanField(default=False)),
                ('young_toddler_group', models.BooleanField(default=False)),
                ('older_toddler_group', models.BooleanField(default=False)),
                ('preschooler_group', models.BooleanField(default=False)),
                ('school_age_group', models.BooleanField(default=False)),
                ('age_groups', models.ManyToManyField(to='daycares.AgeGroup')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=75, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('child', models.ManyToManyField(to='daycares.Child')),
                ('selected_daycare', models.ManyToManyField(to='daycares.Daycare')),
            ],
        ),
        migrations.CreateModel(
            name='DaycareReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=120, null=True)),
                ('review_rating', models.IntegerField(default=0)),
                ('daycare', models.ManyToManyField(default=None, to='daycares.Daycare')),
                ('parent', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='daycares.parent')),
            ],
        ),
    ]
