# Generated by Django 3.2.3 on 2021-05-26 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='agegroup',
            name='group_name',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='agegrouproles',
            name='group_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='daycares.agegroup'),
        ),
        migrations.AddField(
            model_name='daycare',
            name='age_groups',
            field=models.ManyToManyField(to='daycares.AgeGroup'),
        ),
        migrations.AddField(
            model_name='daycare',
            name='infant_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daycare',
            name='older_toddler_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daycare',
            name='preschooler_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daycare',
            name='school_age_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daycare',
            name='street_address',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='young_toddler_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agegrouproles',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='daycares.child'),
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='daycares.child'),
        ),
    ]
