# Generated by Django 3.1.8 on 2021-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycare',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
