# Generated by Django 3.2.3 on 2021-05-26 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0002_auto_20210526_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='selected_daycare',
            field=models.ManyToManyField(to='daycares.Daycare'),
        ),
        migrations.AddField(
            model_name='parent',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='street_address',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='DayCareReview',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='daycares.parent')),
                ('daycare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daycares.daycare')),
            ],
        ),
    ]
