# Generated by Django 3.1.8 on 2021-06-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0002_remove_daycarereview_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
