# Generated by Django 3.1.8 on 2021-06-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0002_auto_20210601_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycare',
            name='max_cost_infant',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='max_cost_old_T',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='max_cost_preschool',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='max_cost_youth_T',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='min_cost_infant',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='min_cost_old_T',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='min_cost_preschool',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='min_cost_youth_T',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
