# Generated by Django 3.1.8 on 2021-05-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0002_auto_20210528_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycare',
            name='max_cost_estimate',
        ),
        migrations.RemoveField(
            model_name='daycare',
            name='min_cost_estimate',
        ),
        migrations.AddField(
            model_name='daycare',
            name='max_cost_infant',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='max_cost_old_T',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='max_cost_preschool',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='max_cost_youth_T',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='min_cost_infant',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='min_cost_old_T',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='min_cost_preschool',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='daycare',
            name='min_cost_youth_T',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
