# Generated by Django 3.2.3 on 2021-05-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0002_alter_parent_selected_daycare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='selected_daycare',
            field=models.ManyToManyField(blank=True, to='daycares.Daycare'),
        ),
    ]
