# Generated by Django 3.2.3 on 2021-05-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0003_auto_20210526_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarereview',
            name='review_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daycarereview',
            name='review_text',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
