# Generated by Django 3.2.3 on 2021-05-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0004_auto_20210526_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='daycares.agegroup'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
