# Generated by Django 3.2.3 on 2021-05-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0005_auto_20210526_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(to='daycares.Child'),
        ),
    ]
