# Generated by Django 3.2.3 on 2021-05-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0006_auto_20210526_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daycares.agegroup'),
        ),
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='daycares.child'),
        ),
    ]
