# Generated by Django 3.2.3 on 2021-05-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0007_auto_20210526_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='age',
            new_name='age_group',
        ),
    ]
