# Generated by Django 3.2.3 on 2021-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0008_rename_age_child_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegrouproles',
            name='child',
        ),
        migrations.AddField(
            model_name='agegrouproles',
            name='child',
            field=models.ManyToManyField(to='daycares.Child'),
        ),
    ]
