# Generated by Django 3.2.3 on 2021-05-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0009_auto_20210526_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegrouproles',
            name='child',
        ),
        migrations.AddField(
            model_name='agegrouproles',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='daycares.child'),
        ),
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(default=None, to='daycares.Child'),
        ),
    ]
