# Generated by Django 3.2.3 on 2021-05-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycares', '0010_auto_20210526_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(blank=True, to='daycares.Child'),
        ),
    ]
