# Generated by Django 3.2.3 on 2021-05-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210526_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daycare_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
