# Generated by Django 3.2.3 on 2021-05-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_daycare_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daycare_name',
        ),
    ]
